// cn-mapping.js — 短语 → 中文对应词映射表
module.exports = {
  // ===== 7上 =====
  "7a": {
    "Beijing roast duck": ["北京烤鸭"],
    "CPC Founding Day": ["建党节"],
    "Chinese chess": ["中国象棋"],
    "Mapo tofu": ["麻婆豆腐"],
    "National Day": ["国庆节"],
    "PLA Day": ["建军节"],
    "You're welcome": ["不客气"],
    "a lot": ["非常","很"],
    "a lot of": ["很多","一批","一大批"],
    "act out": ["表演"],
    "at night": ["晚上","晚","夜晚"],
    "at weekends": ["周末"],
    "be across from": ["对面"],
    "be at home": ["在家"],
    "be at school": ["在学校"],
    "be at the back of": ["后面"],
    "be different from": ["不一样","不","不同"],
    "be good at": ["擅长"],
    "be good with": ["很会","相处","善于"],
    "be in class": ["上课","上","课上"],
    "be in front of": ["前面","前"],
    "be in the middle": ["中间"],
    "be interested in": ["感兴趣"],
    "be next to": ["紧挨着"],
    "be on duty": ["值日"],
    "be similar to": ["差不多","类似于"],
    "blow out": ["吹灭"],
    "bye for now": ["再见"],
    "class teacher": ["班主任"],
    "daily routines": ["日常安排","日常"],
    "do exercise": ["锻炼身体","锻炼"],
    "do exercises": ["做早操","做热身运动","做","做了","热身运动"],
    "each other": ["互相"],
    "every day": ["每天"],
    "fall in love with": ["爱上了","爱上","会上"],
    "first name": ["名字"],
    "fishing rod": ["钓鱼竿"],
    "for example": ["比如"],
    "full name": ["全名"],
    "get dressed": ["穿好衣服","穿","穿上"],
    "get to know": ["了解"],
    "get up": ["起床","起"],
    "go hiking": ["爬山","山","徒步"],
    "go to bed": ["睡觉"],
    "have fun": ["玩得很开心","玩得","玩得特别尽兴"],
    "help sb with": ["帮","做家务"],
    "home economics": ["家政课","家政"],
    "hot pot": ["火锅"],
    "ice hockey": ["冰球"],
    "in the future": ["将来","来","未来"],
    "last name": ["姓"],
    "listen to": ["听"],
    "look at": ["看"],
    "make a wish": ["许了一个愿","许","许愿"],
    "make friends": ["交了","朋友"],
    "make use of": ["利用"],
    "more than": ["多","远超"],
    "musical instrument": ["乐器"],
    "next time": ["下次"],
    "ping-pong bat": ["乒乓球拍"],
    "play Chinese chess": ["下中国象棋","中国象棋","下","象棋"],
    "play ping-pong": ["打乒乓球"],
    "play the guitar": ["弹吉他","吉他","弹着"],
    "prepare sth for": ["准备"],
    "put up": ["贴","竖起"],
    "sports field": ["操场","场","运动场"],
    "take a photo": ["拍了","照片"],
    "take a shower": ["冲个澡","沐浴"],
    "take photos": ["拍照"],
    "the Great Wall": ["长城"],
    "work out": ["解不出来","突破"],
  },

  // ===== 7下 =====
  "7b": {
    "Bright Peak": ["光明顶"],
    "Central Park": ["中央公园"],
    "Dongpo pork": ["东坡肉"],
    "Dragon Boat Festival": ["端午节"],
    "Gongbao chicken": ["宫保鸡丁"],
    "Mount Huangshan": ["黄山"],
    "a few": ["几个","几","几只"],
    "after all": ["毕竟"],
    "agree with": ["同意"],
    "all over": ["到处"],
    "around the world": ["全世界","世界"],
    "at first": ["起初"],
    "at the moment": ["此刻"],
    "be absent from": ["没来","缺了"],
    "be at the end": ["尽头","终点"],
    "be at the start": ["起点"],
    "be at the top": ["最上面","峰顶"],
    "be full of": ["装满","满","充满了"],
    "be in a hurry": ["着急","匆匆"],
    "be in danger": ["危险"],
    "be in high spirits": ["情绪很高","情绪"],
    "be late for": ["迟到"],
    "be made of": ["木头做","制成"],
    "be on time": ["准时"],
    "be over there": ["那边"],
    "beach volleyball": ["沙滩排球"],
    "because of": ["因为","由于"],
    "belong to": ["属于"],
    "bite through": ["咬穿"],
    "call back": ["回电话"],
    "come out": ["出来了","出","问世"],
    "cut down": ["砍伐","砍","砍掉"],
    "drop off": ["送"],
    "excuse me": ["劳驾"],
    "fast food": ["快餐"],
    "feel like": ["想","像"],
    "fish and chips": ["炸鱼薯条"],
    "focus on": ["集中注意力","中","专注于"],
    "from… to…": ["从","到"],
    "get out": ["出来"],
    "go away": ["走开"],
    "go on a trip": ["郊游","旅行"],
    "go with": ["很配","配","相配"],
    "hang out": ["闲逛"],
    "hardly ever": ["几乎从不"],
    "have to": ["必须","不得不"],
    "hold on": ["等一下","一下","稍等"],
    "in the end": ["最后","最"],
    "instead of": ["而不是","不用","代替"],
    "jump rope": ["跳绳"],
    "jump the queue": ["插队"],
    "laugh at": ["嘲笑"],
    "leave a message": ["留言"],
    "long ago": ["很久以前"],
    "look after": ["照看"],
    "look forward to": ["期盼"],
    "lucky you": ["幸运"],
    "make a promise": ["答应","作出"],
    "make money": ["赚钱","赚","赚了钱"],
    "make progress": ["进步","进","取得"],
    "make sb's bed / make the bed": ["铺","睡袋"],
    "make sb’s bed / make the bed": ["铺床","铺"],
    "meet up": ["碰面"],
    "mobile phone": ["手机"],
    "not… at all": ["一点儿也不"],
    "of course": ["当然"],
    "once upon a time": ["很久很久以前"],
    "one another": ["互相"],
    "only if": ["只有"],
    "pick up": ["捡起来","起","吊起"],
    "put on": ["穿上"],
    "quite a": ["真是一个","是","相当"],
    "rain or shine": ["无论晴雨","无","风雨无阻"],
    "rest area": ["休息区"],
    "right now": ["现在","立刻"],
    "run after": ["追"],
    "rush hour": ["高峰"],
    "search for": ["找","搜寻"],
    "set… free": ["放归"],
    "side by side": ["并肩"],
    "soft drink": ["软饮料"],
    "some day": ["有一天","有","有朝一日"],
    "stay in": ["待在家里","待在"],
    "succeed in doing sth": ["成功地"],
    "such as": ["比如"],
    "take a message": ["捎个口信","口信","记录","捎口信"],
    "take care of": ["照顾"],
    "take part in": ["参加"],
    "tell the truth": ["说实话"],
    "think about": ["考虑"],
    "think of": ["想起","认为"],
    "time zone": ["时区","时"],
    "to sb's surprise": ["惊讶的是"],
    "to sb’s surprise": ["意外"],
    "too many": ["太多的","太多"],
    "too much": ["太多","多","过多"],
    "too… to…": ["太小了","不能"],
    "try on": ["试穿"],
    "turn off": ["关灯","关","关闭"],
    "used to": ["常常","常","过去常"],
    "what about": ["怎么样"],
    "work on": ["做","致力于"],
    "work out": ["锻炼","难题"],
    "working day": ["工作日"],
    "write down": ["写下来"],
  },

  // ===== 8上 =====
  "8a": {
    "Guest-Greeting Pine": ["迎客松"],
    "Guoqiao Rice Noodles": ["过桥米线"],
    "Moscow Metro": ["莫斯科地铁"],
    "Red Square": ["红场"],
    "Sea of Clouds": ["云海"],
    "World War II": ["第二次世界大战"],
    "add sb to sth": ["加"],
    "along with sb/sth": ["一起","共同","其中包括"],
    "argue with sb": ["争论"],
    "as long as": ["只要"],
    "at least": ["至少"],
    "be careful with": ["小心"],
    "be connected with/to": ["连接","连","相连"],
    "be home to sb/sth": ["家园"],
    "be in the sun": ["太阳底下","太阳","太阳下","在太阳下"],
    "be nothing but": ["只不过","只","其实"],
    "be ready to do sth": ["准备好","准备","准备就绪"],
    "be tired of": ["厌倦","厌","厌烦了"],
    "be up to": ["由你决定","决","取决于"],
    "be yourself": ["做你自己","自己","做自己"],
    "be/feel free": ["随意"],
    "benefit…from…": ["受益","益"],
    "by accident": ["偶然"],
    "care about": ["关心"],
    "clean up": ["打扫","清理"],
    "come over": ["来我家","来","来过"],
    "congratulations on": ["祝贺","恭喜"],
    "cut sth in/into sth": ["切成"],
    "cut up": ["切碎","切","切块"],
    "depend on/upon": ["依赖"],
    "do with": ["处理","利用"],
    "draw to a close": ["结束","落下帷幕"],
    "drop sb a line": ["写信","写"],
    "emotional intelligence": ["情商"],
    "face to face": ["面对面"],
    "fight against sb": ["作斗争"],
    "fill…with…": ["装饰满","装","装满"],
    "find out": ["查出","出","找出"],
    "folding fan": ["折扇"],
    "for this reason": ["因此","因","因为这个原因","因为"],
    "get together": ["聚在一起"],
    "give sb a lift": ["载我一程","我","搭顺风车"],
    "go boating": ["划船"],
    "go shopping": ["购物","逛街"],
    "hang up": ["挂了电话","电话","挂断"],
    "have sth in common": ["共同点","共","有共同"],
    "have to do with sb/sth": ["没关系","关","有关"],
    "hot and sour soup": ["酸辣汤"],
    "in fact": ["其实"],
    "in order to": ["为了"],
    "in person": ["亲自"],
    "keep on doing sth": ["继续","坚持"],
    "keep…away from…": ["远离","离","防止"],
    "last but not least": ["最后但同样重要"],
    "lend sb a hand": ["帮我一下","帮","冒着风雪"],
    "living room": ["客厅"],
    "look for": ["找"],
    "make a mistake": ["犯错"],
    "make sure": ["确保"],
    "make up with sb": ["和好"],
    "mix…with…": ["混合"],
    "move on (to sth)": ["开始准备","转向"],
    "no matter": ["不管","无论"],
    "one by one": ["一个一个","一","一把一把地","一把"],
    "outer space": ["外太空"],
    "pay attention to": ["注意"],
    "play a part": ["发挥作用","发挥"],
    "play a role in": ["起着重要作用","扮演"],
    "pour sth into sth": ["倒进","注入"],
    "put out": ["扑灭"],
    "put sth back": ["放回"],
    "reach for": ["伸手去拿","手","抬手","取下"],
    "right away": ["马上","上","立刻"],
    "run low": ["快吃完","走低"],
    "share sth with sb": ["分享"],
    "show interest in": ["兴趣"],
    "show sb around": ["参观","逛","逛了逛"],
    "silver lining": ["银边","转机","一线希望"],
    "social media": ["社交媒体"],
    "spare time": ["空闲时间","时间","闲暇时间","闲暇"],
    "steamed fish": ["清蒸鱼","清蒸"],
    "stick to sth": ["坚持"],
    "take a walk": ["散步"],
    "take notes": ["记笔记","记"],
    "take over": ["接管"],
    "take place": ["举行"],
    "take sb’s breath away": ["屏住了呼吸"],
    "take up": ["开始学","开始","拿起"],
    "text message": ["短信"],
    "thanks to": ["多亏"],
    "the Arctic": ["北极"],
    "the Victory Museum": ["胜利博物馆"],
    "the movies": ["看电影"],
    "thousands of": ["成千上万"],
    "treasure hunt": ["寻宝"],
    "try one's best": ["尽最大努力","尽力"],
    "try one’s best": ["尽力","尽"],
    "turn around": ["转过身","转","转头"],
    "warm up": ["热身","热"],
    "worry about": ["担心","生怕"],
  },

  // ===== 8下 =====
  "8b": {
    "a bit": ["有点"],
    "a good read": ["好看","好","好书"],
    "alarm clock": ["闹钟"],
    "all of a sudden": ["突然"],
    "as a result": ["结果"],
    "as soon as": ["一","就"],
    "as well": ["也"],
    "be about to": ["正要"],
    "be all smiles": ["笑容满面","笑","笑得合不拢嘴"],
    "be based on": ["根据","基于"],
    "be familiar with": ["熟悉"],
    "be hard on": ["苛刻","持批评态度","批评"],
    "be in low spirits": ["情绪很低","情绪","情绪低","情绪低落"],
    "be in need": ["患难见真情","难","需要帮助","帮助"],
    "be in one's forties": ["四十多"],
    "be on fire": ["着火","火","燃起"],
    "be on the go": ["忙"],
    "be on top of the world": ["高兴极了","无比振奋","欣喜若狂"],
    "be out of breath": ["气喘吁吁"],
    "be proud of": ["骄傲","感到自豪"],
    "be scared of": ["怕"],
    "be up to": ["由你决定","决","取决于"],
    "be/get used to": ["习惯"],
    "bit by bit": ["一点一点"],
    "by the time": ["到"],
    "catch fire": ["着火","火","燃烧起来"],
    "clear the air": ["消除了误会","消除","消除了","消除误会"],
    "come along": ["跟"],
    "day by day": ["一天天"],
    "deal with": ["处理"],
    "do chores": ["做家务"],
    "dream of": ["梦想"],
    "eat out": ["出去吃","吃","下馆子"],
    "ever since": ["自从"],
    "except for": ["除了"],
    "feel blue": ["心情不好","难过","感到无比悲伤"],
    "first aid": ["急救"],
    "from now on": ["从现在起","从","从今往后"],
    "from time to time": ["偶尔","时不时地"],
    "get across": ["理解"],
    "get into": ["考上","上","迷上了"],
    "get lost": ["迷路","迷","迷了路"],
    "get over": ["克服","走出"],
    "get to one's feet": ["站了起来","起来"],
    "give it a go": ["试试","试","放手一试"],
    "give up": ["放弃"],
    "go a long way": ["有用","有","深远"],
    "go off": ["响了","响","响起"],
    "go on an outing": ["郊游"],
    "go wrong": ["出故障","出","出点差错"],
    "hand out": ["分发"],
    "hear from": ["收到","盼着","消息"],
    "hear of": ["听说"],
    "help out": ["帮忙"],
    "in future": ["以后","后","今后"],
    "in return": ["回报"],
    "in time": ["及时"],
    "keep ... off": ["勿践踏","挡住"],
    "kick oneself": ["后悔","悔","自责"],
    "let down": ["失望"],
    "lie down": ["躺下","躺"],
    "lock up": ["锁好","围了起来"],
    "look on the bright side": ["乐观","往好处想"],
    "make a difference": ["有所作为","作用","改变"],
    "make preparations": ["做准备"],
    "most of all": ["最"],
    "no way": ["没门儿","简直不可能"],
    "not only ... but also ...": ["不仅","还"],
    "on purpose": ["故意"],
    "once in a while": ["偶尔"],
    "pass away": ["去世"],
    "plenty of": ["很多","多","充足的"],
    "pull together": ["齐心协力"],
    "put oneself in sb's shoes": ["设身处地","站在","角度"],
    "reduce by half": ["降低了一半","了一半","减少了一半","减少","减半"],
    "science fiction": ["科幻小说"],
    "security guard": ["保安"],
    "serving chopsticks": ["公筷"],
    "shout at sb": ["大喊大叫","大叫"],
    "shut sb/sth away": ["埋藏","藏"],
    "sign up": ["报名"],
    "sit up": ["坐了起来","坐"],
    "so ... that": ["太简单了","一下子就做完","如此","以至于"],
    "so far": ["到目前为止","目前","截至目前"],
    "square kilometre": ["平方公里"],
    "stop ... from doing": ["无法出门","出","阻止"],
    "stop short": ["突然停住","突然","突然停住脚步"],
    "suffer from": ["受"],
    "take a deep breath": ["深呼吸","深","深吸一口气"],
    "take a seat": ["坐下"],
    "take back": ["收回"],
    "take one's temperature": ["量了体温","体温","测量体温"],
    "the elderly": ["老人","人","长者"],
    "turn on": ["打开","开","开启"],
    "wake up": ["醒来"],
    "what's more": ["而且"],
  },

  // ===== 9上 =====
  "9a": {
    "bring about": ["带来"],
  },

  // ===== 9下 =====
  "9b": {
  },

};
